<?php namespace CLOUDMEISTER\CMX\Buero; defined('ABSPATH') or die('Oxytocin!');


register_post_type('banken', [
	'label' => 'banken',
	'singular_name' => 'Banken',
	'labels' => [
		'menu_name' => 'Banken',
		'all_items' => 'Übersicht',
		'add_new' => 'Add bank',
		'add_new_item' => 'Neue Transaktion',
		'edit_item' => 'Edit bank',
		'new_item' => 'New bank',
		'view_item' => 'View bank',
		'view_items' => 'View banken',
		'search_item' => 'Search banken',
		'not_found' => 'No bank found',
		'not_found_in_trash' => 'No bank found',
		'parent_item_colon' => 'Parent item',
		'featured_image' => 'Featured image',
		'set_featured_image' => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image' => 'Use featured image',
		'archives' => 'Archives',
		'insert_into_item' => 'Insert',
		'uploaded_to_this_item' => 'Upload',
		'filter_items_list' => 'Filter banken list',
		'items_list_navigation' => 'Navigation list banken',
		'items_list' => 'List banken',
		'filter_by_date' => 'Filter by date',
		'item_published' => 'bank published',
		'item_published_privately' => 'bank published privately',
		'item_reverted_to_draft' => 'bank reverted to draft',
		'item_scheduled' => 'bank scheduled',
		'item_updated' => 'bank updated',
	],
	'public' => true,
	'publicly_queryable' => true,
	'query_var' => true,
	'menu_icon' => 'dashicons-bank',
	'rewrite' => true,
	'capability_type' => 'post',
	'hierarchical' => null,
	'menu_position' => 35,
	'supports' => [
	'title',
	'editor',
	'thumbnail',
	'excerpt',
	],
	'has_archive' => true,
	'show_in_rest' => true,
	'show_ui' => true,
	'show_in_menu' => true,
	'show_in_nav_menus' => true,
	'show_in_admin_bar' => true,
	'rest_base' => null,
	'with_front' => true,
	'custom_rewrite' => null,
	'custom_query_var' => null,
	'front_url_prefix' => 'banken',
	'show_in_graphql' => true,
	'graphql_single_name' => 'bank',
	'graphql_plural_name' => 'banken',
	]);
