ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN apt-get update && apt-get install -y libc-client-dev libkrb5-dev \
    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install imap
