<?php namespace CLOUDMEISTER\CMX\Buero; defined('ABSPATH') or die('Oxytocin!');


register_post_type('ausgaben', ['label' => 'ausgaben','singular_name' => 'Ausgaben',
	'labels' => [
		'menu_name' => 'Ausgaben',
		'all_items' => 'Übersicht',
		'add_new' => 'Add ausgabe',
		'add_new_item' => 'Neue Ausgabe',
		'edit_item' => 'Edit ausgabe',
		'new_item' => 'New ausgabe',
		'view_item' => 'View ausgabe',
		'view_items' => 'View ausgaben',
		'search_item' => 'Search ausgaben',
		'not_found' => 'No ausgabe found',
		'not_found_in_trash' => 'No ausgabe found',
		'parent_item_colon' => 'Parent item',
		'featured_image' => 'Featured image',
		'set_featured_image' => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image' => 'Use featured image',
		'archives' => 'Archives',
		'insert_into_item' => 'Insert',
		'uploaded_to_this_item' => 'Upload',
		'filter_items_list' => 'Filter ausgaben list',
		'items_list_navigation' => 'Navigation list ausgaben',
		'items_list' => 'List ausgaben',
		'filter_by_date' => 'Filter by date',
		'item_published' => 'ausgabe published',
		'item_published_privately' => 'ausgabe published privately',
		'item_reverted_to_draft' => 'ausgabe reverted to draft',
		'item_scheduled' => 'ausgabe scheduled',
		'item_updated' => 'ausgabe updated',
	],
	'public' => true,
	'publicly_queryable' => true,
	'query_var' => true,
	'menu_icon' => 'dashicons-money-alt',
	'rewrite' => true,
	'capability_type' => 'post',
	'hierarchical' => null,
	'menu_position' => 25,
	'supports' => ['title','editor','thumbnail','excerpt',],
	'has_archive' => true,
	'show_in_rest' => true,
	'show_ui' => true,
	'show_in_menu' => true,
	'show_in_nav_menus' => true,
	'show_in_admin_bar' => true,
	'rest_base' => null,
	'with_front' => true,
	'custom_rewrite' => null,
	'custom_query_var' => null,
	'front_url_prefix' => 'ausgaben',
	'show_in_graphql' => true,
	'graphql_single_name' => 'ausgabe',
	'graphql_plural_name' => 'ausgaben',
]);



register_taxonomy(
	'ausgabe_type',
	[
	           'ausgaben',

	],
	[
	           'hierarchical' => true,
           'label' => 'ausgaben_type',
           'singular_label' => 'ausgabe_type',
           'show_ui' => true,
           'query_var' => null,
           'show_admin_column' => null,
           'show_in_rest' => true,
           'rewrite' => null,
        'labels' => [
           'name' => 'Aufwände',
           'singular_name' => 'ausgabe_type',
           'search_items' => 'Search ausgaben_type',
           'popular_items' => 'Popular ausgaben_type',
           'all_items' => 'All ausgaben_type',
           'parent_item' => 'Parent ausgabe_type',
           'parent_item_colon' => 'Parent item',
           'edit_item' => 'Edit',
           'view_item' => 'View',
           'update_item' => 'Update ausgabe_type',
           'add_new_item' => 'Add new ausgabe_type',
           'new_item_name' => 'New ausgabe_type',
           'separate_items_with_commas' => 'Separate ausgaben_type with commas',
           'add_or_remove_items' => 'Add or remove ausgaben_type',
           'choose_from_most_used' => 'Choose from most used ausgabe_type',
           'not_found' => 'No ausgabe_type found',
           'no_terms' => 'No ausgaben_type',
           'filter_by_item' => 'Filter by ausgabe_type',
           'items_list_navigation' => 'Navigation list ausgaben_type',
           'items_list' => 'List ausgaben_type',
           'most_used' => 'Most used ausgaben_type',
           'back_to_items' => 'Back to ausgaben_type',
        ],
           'public' => true,
           'publicly_queryable' => true,
           'show_in_menu' => true,
           'show_in_nav_menus' => true,
           'rest_base' => null,
           'rest_controller_class' => null,
           'show_tagcloud' => true,
           'show_in_quick_edit' => true,
        'capabilities' => [
           'manage_terms',
           'edit_terms',
           'delete_terms',
           'assign_terms',
        ],
           'custom_rewrite' => null,
           'custom_query_var' => null,
           'default_term' => null,
           'sort' => null,

]);
